---
title: "Let’s Generalize About Fans"
author: "Faith Benamy"
date: "4/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('config.R')
```

```{r}
library(tidyverse)
library(rtweet)
library(fuzzywuzzyR) 
library(rlist)
```

```{r}
top_5 <- search_tweets("#CrazyExTop5", n = 1000, include_rts = FALSE) 
``` 

```{r}
fav_song <- search_tweets("#FavoriteCrazyExGirlfriendSong", n = 1000, include_rt = FALSE)
```
```{r}
cleaned_fav <- fav_song %>% 
                pull(text) 
```

```{r}
cleaned_rankings <- top_5 %>% 
                      pull(text) %>%
                      str_extract_all("[12345][^{]+[12345][^{]+(\\z)") %>%
                      unlist() %>% 
                      str_remove_all("^\\n") %>% 
                      str_remove_all("(\\n)[^\\n15]+$") %>% 
                      str_remove_all("[^\x01-\x7F]") %>%
                      str_replace_all("([a-z\\?!\\.]) {1,}([12345])",
                                      "\\1\n\\2") %>%
                      str_split("\\n") %>% 
                      unlist() %>%
                      .[str_detect(., "([12345](\\.|\\))) [A-Za-z]")] %>% 
                      str_trim()
```

```{r}
rank_song_df <- cleaned_rankings %>% 
                  str_to_lower() %>% 
                  tibble(cleaned_tweets = .) %>% 
                  separate(cleaned_tweets, c("rank", "song_name"), 
                           sep = "\\.|\\) ") %>%
                  mutate(song_name = str_remove_all(song_name,
                                                    "[[:punct:]]")) %>% 
                  mutate(song_name = str_remove_all(song_name, 
                                                    "httpst") %>% 
                  str_trim()) %>% 
                  mutate(song_name = str_remove_all(song_name, "crazyextop5")) %>% 
                  mutate(rank = str_sub(rank, start = 1, end = 1)) %>% 
                  filter(str_length(song_name) >5, song_name != "get it trending youths", str_detect(song_name," "))

write_csv(rank_song_df, "rank_song_df.csv")
```

```{r}
songs_df <- read_csv("track_info.csv" ) %>%  
              mutate(song_name_lower = str_to_lower(name)) %>% 
              mutate(song_name_lower = str_remove_all(song_name_lower,
                                                      "[[:punct:]]")) %>% 
              mutate(song_name_lower = str_remove(song_name_lower,
                                                  "(feat.*)"))

#songs_df <- rbind(songs_df,list.append(rep(NA, 18), "Season 4", "['Rachel Bloom']", "eleven o'clock"))

```

```{r}
fuzzy_match_df <- rank_song_df %>% 
                    rowwise() %>% 
                    mutate(fuzzy_match = as.character(GetCloseMatches(string =
                                             song_name,
                                             sequence_strings =
                                              songs_df$song_name_lower,
                                             n = 3, cutoff = 0.6))[1]) %>%
                    mutate(fuzzy_match = case_when(
                      song_name == "fit hot guys" ~ 
                        "fit hot guys have problems too", 
                      str_detect(song_name,"child star") ~ "i want to be a child star",
                      song_name == "trapped in a car" ~ "trapped in a car with someone you dont want to be trapped in a car with", 
                      str_detect(song_name, "you ruin") ~ "you stupid bitch",
                      song_name == "strip it all away" ~ "strip away my strip away my conscience", 
                      song_name == "devil winds" ~ "santa ana winds pt 15", 
                      song_name == "s1 theme song" ~ "crazy exgirlfriend theme",  
                      song_name == "tidying up song dont judge its amazing" ~
                        "how to tidy up",
                      is.na(fuzzy_match) ~ as.character(GetCloseMatches(
                                             string= str_sub(song_name, 
                                                             1, 20),
                                             sequence_strings =
                                              songs_df$song_name_lower,
                                             n = 3, cutoff = 0.58))[1],
                      TRUE ~ fuzzy_match))
                             
```


```{r}
reshape_df <- fuzzy_match_df %>%
                filter(!is.na(fuzzy_match)) %>% 
                select(fuzzy_match, rank) %>% 
                group_by(fuzzy_match, rank) %>%
                summarize(n = n()) %>%
                spread(rank, n)
```

```{r}
View(fuzzy_match_df %>% filter(is.na(fuzzy_match)))
```
